// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {review} from '../models';
import {domain} from '../models';
import {context} from '../models';

export function ApplyRotation(arg1:number,arg2:string):Promise<void>;

export function Browse(arg1:string):Promise<review.BrowseResponse>;

export function BrowseDialog():Promise<review.PathResponse>;

export function CancelExport():Promise<void>;

export function ExiftoolDialog():Promise<review.PathResponse>;

export function ExportFiles(arg1:Array<string>,arg2:string,arg3:boolean):Promise<void>;

export function ExportLogs():Promise<void>;

export function ExportSelection(arg1:string,arg2:number,arg3:string,arg4:boolean):Promise<void>;

export function FlushPersistence():Promise<void>;

export function GetAnalysisProgress():Promise<review.AnalysisProgressResponse>;

export function GetAppState():Promise<review.AppState>;

export function GetBookmarks():Promise<review.BookmarkResponse>;

export function GetConfig():Promise<domain.Config>;

export function GetDuplicates(arg1:number):Promise<Array<any>>;

export function GetFile(arg1:number,arg2:boolean):Promise<review.FileResponse>;

export function GetFilteredIndices(arg1:Record<string, string>):Promise<review.FilteredIndicesResponse>;

export function GetFilters():Promise<review.FilterValuesResponse>;

export function GetFolders():Promise<Array<review.FolderInfo>>;

export function GetHistory():Promise<Array<string>>;

export function GetLabelIndices(arg1:number):Promise<review.FilteredIndicesResponse>;

export function GetStarredIndices():Promise<review.FilteredIndicesResponse>;

export function GetStats():Promise<review.AppStats>;

export function ListTrash():Promise<review.TrashListResponse>;

export function Log(arg1:string,arg2:string,arg3:Record<string, any>):Promise<void>;

export function OpenConfigFolder():Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function PrioritizeIndices(arg1:Array<number>):Promise<void>;

export function Quit():Promise<void>;

export function ReanalyzeMetadata(arg1:number):Promise<review.FileResponse>;

export function Refresh(arg1:number):Promise<review.ActionResponse>;

export function RemoveHistory(arg1:string):Promise<void>;

export function ResetAppCache():Promise<void>;

export function ResetLabels():Promise<void>;

export function ResetStars():Promise<void>;

export function RestoreFromTrash(arg1:Array<string>):Promise<review.RestoreResponse>;

export function RevealInExplorer(arg1:number):Promise<void>;

export function Rotate(arg1:number,arg2:string,arg3:string):Promise<review.ActionResponse>;

export function RotateReset(arg1:number,arg2:string):Promise<review.ActionResponse>;

export function SavePosition(arg1:number):Promise<void>;

export function SearchStream(arg1:string):Promise<void>;

export function SetLabel(arg1:number,arg2:string,arg3:Array<string>,arg4:number):Promise<any>;

export function SetSortOrder(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function SysCheck():Promise<review.SysCheckResponse>;

export function ToggleStar(arg1:number,arg2:string,arg3:Array<string>,arg4:boolean):Promise<any>;

export function Trash(arg1:number,arg2:string,arg3:Array<string>):Promise<review.ActionResponse>;

export function Undo():Promise<review.UndoResponse>;

export function UpdateConfig(arg1:domain.Config):Promise<void>;
