// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyRotation(arg1, arg2) {
  return window['go']['review']['App']['ApplyRotation'](arg1, arg2);
}

export function Browse(arg1) {
  return window['go']['review']['App']['Browse'](arg1);
}

export function BrowseDialog() {
  return window['go']['review']['App']['BrowseDialog']();
}

export function CancelExport() {
  return window['go']['review']['App']['CancelExport']();
}

export function ExiftoolDialog() {
  return window['go']['review']['App']['ExiftoolDialog']();
}

export function ExportFiles(arg1, arg2, arg3) {
  return window['go']['review']['App']['ExportFiles'](arg1, arg2, arg3);
}

export function ExportLogs() {
  return window['go']['review']['App']['ExportLogs']();
}

export function ExportSelection(arg1, arg2, arg3, arg4) {
  return window['go']['review']['App']['ExportSelection'](arg1, arg2, arg3, arg4);
}

export function FlushPersistence() {
  return window['go']['review']['App']['FlushPersistence']();
}

export function GetAnalysisProgress() {
  return window['go']['review']['App']['GetAnalysisProgress']();
}

export function GetAppState() {
  return window['go']['review']['App']['GetAppState']();
}

export function GetBookmarks() {
  return window['go']['review']['App']['GetBookmarks']();
}

export function GetConfig() {
  return window['go']['review']['App']['GetConfig']();
}

export function GetDuplicates(arg1) {
  return window['go']['review']['App']['GetDuplicates'](arg1);
}

export function GetFile(arg1, arg2) {
  return window['go']['review']['App']['GetFile'](arg1, arg2);
}

export function GetFilteredIndices(arg1) {
  return window['go']['review']['App']['GetFilteredIndices'](arg1);
}

export function GetFilters() {
  return window['go']['review']['App']['GetFilters']();
}

export function GetFolders() {
  return window['go']['review']['App']['GetFolders']();
}

export function GetHistory() {
  return window['go']['review']['App']['GetHistory']();
}

export function GetLabelIndices(arg1) {
  return window['go']['review']['App']['GetLabelIndices'](arg1);
}

export function GetStarredIndices() {
  return window['go']['review']['App']['GetStarredIndices']();
}

export function GetStats() {
  return window['go']['review']['App']['GetStats']();
}

export function ListTrash() {
  return window['go']['review']['App']['ListTrash']();
}

export function Log(arg1, arg2, arg3) {
  return window['go']['review']['App']['Log'](arg1, arg2, arg3);
}

export function OpenConfigFolder() {
  return window['go']['review']['App']['OpenConfigFolder']();
}

export function OpenFolder(arg1) {
  return window['go']['review']['App']['OpenFolder'](arg1);
}

export function PrioritizeIndices(arg1) {
  return window['go']['review']['App']['PrioritizeIndices'](arg1);
}

export function Quit() {
  return window['go']['review']['App']['Quit']();
}

export function ReanalyzeMetadata(arg1) {
  return window['go']['review']['App']['ReanalyzeMetadata'](arg1);
}

export function Refresh(arg1) {
  return window['go']['review']['App']['Refresh'](arg1);
}

export function RemoveHistory(arg1) {
  return window['go']['review']['App']['RemoveHistory'](arg1);
}

export function ResetAppCache() {
  return window['go']['review']['App']['ResetAppCache']();
}

export function ResetLabels() {
  return window['go']['review']['App']['ResetLabels']();
}

export function ResetStars() {
  return window['go']['review']['App']['ResetStars']();
}

export function RestoreFromTrash(arg1) {
  return window['go']['review']['App']['RestoreFromTrash'](arg1);
}

export function RevealInExplorer(arg1) {
  return window['go']['review']['App']['RevealInExplorer'](arg1);
}

export function Rotate(arg1, arg2, arg3) {
  return window['go']['review']['App']['Rotate'](arg1, arg2, arg3);
}

export function RotateReset(arg1, arg2) {
  return window['go']['review']['App']['RotateReset'](arg1, arg2);
}

export function SavePosition(arg1) {
  return window['go']['review']['App']['SavePosition'](arg1);
}

export function SearchStream(arg1) {
  return window['go']['review']['App']['SearchStream'](arg1);
}

export function SetLabel(arg1, arg2, arg3, arg4) {
  return window['go']['review']['App']['SetLabel'](arg1, arg2, arg3, arg4);
}

export function SetSortOrder(arg1) {
  return window['go']['review']['App']['SetSortOrder'](arg1);
}

export function Startup(arg1) {
  return window['go']['review']['App']['Startup'](arg1);
}

export function SysCheck() {
  return window['go']['review']['App']['SysCheck']();
}

export function ToggleStar(arg1, arg2, arg3, arg4) {
  return window['go']['review']['App']['ToggleStar'](arg1, arg2, arg3, arg4);
}

export function Trash(arg1, arg2, arg3) {
  return window['go']['review']['App']['Trash'](arg1, arg2, arg3);
}

export function Undo() {
  return window['go']['review']['App']['Undo']();
}

export function UpdateConfig(arg1) {
  return window['go']['review']['App']['UpdateConfig'](arg1);
}
